CREATE TABLE API_FLIGHTS (
  ID            BIGINT PRIMARY KEY,
  ORIGIN        VARCHAR(128) NOT NULL,
  DESTINATION   VARCHAR(128) NOT NULL,
  AIRLINE       VARCHAR(128) NOT NULL,
  FLIGHT_NUMBER VARCHAR(128) NOT NULL,
  TRAVELER      VARCHAR(128) NOT NULL
);

CREATE TABLE API_CN_AREAS (
  CODE CHAR(6) PRIMARY KEY
  COMMENT '地区编码',
  NAME VARCHAR(32) NOT NULL
  COMMENT '地区名称'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '中国地区';

CREATE TABLE API_US_AREAS (
  CODE CHAR(3) PRIMARY KEY
  COMMENT '地区编码',
  NAME VARCHAR(32) NOT NULL
  COMMENT '地区名称'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '美国地区';

CREATE TABLE API_USERS (
  ID            BIGINT PRIMARY KEY,
  USERNAME      VARCHAR(32)  NOT NULL
  COMMENT '用户名',
  PASSWORD_HASH VARCHAR(128) NOT NULL
  COMMENT '密码(加密过的)',
  STATUS        INT          NOT NULL DEFAULT 1
  COMMENT '状态: 0: 未激活; 1: 激活',
  CREATE_TIME   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '用户';

CREATE UNIQUE INDEX UQ_API_USERS_USERNAME ON API_USERS (USERNAME);
CREATE INDEX IX_API_USERS_STATUS ON API_USERS (STATUS);

CREATE TABLE API_ROLES (
  UID       BIGINT      NOT NULL
  COMMENT '用户ID, 关联API_USERS',
  AUTHORITY VARCHAR(32) NOT NULL
  COMMENT '用户权限'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '用户角色';

CREATE UNIQUE INDEX UQ_API_ROLES_UID_AUTHORITY ON API_ROLES (UID, AUTHORITY);

CREATE TABLE API_USER_DETAILS (
  UID      BIGINT      NOT NULL
  COMMENT '用户ID, 关联API_USERS',
  NICKNAME VARCHAR(64) NOT NULL
  COMMENT '真实姓名',
  GENDER   INT COMMENT '性别: 0: 女; 1: 男',
  BIRTH    DATE COMMENT '生日',
  STATURE  INT COMMENT '身高CM',
  WEIGHT   DOUBLE COMMENT '体重KG',
  PHONE    VARCHAR(32) NOT NULL
  COMMENT '监护人手机',
  ADDRESS  VARCHAR(128) COMMENT '住址',
  REMARKS  VARCHAR(256) COMMENT '备注'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '用户详情';

CREATE UNIQUE INDEX UQ_API_USER_DETAILS ON API_USER_DETAILS (UID);

CREATE TABLE API_ORGANIZATIONS (
  ID        BIGINT PRIMARY KEY,
  PARENT    BIGINT      NOT NULL DEFAULT 0
  COMMENT '父机构, 为0表示顶端',
  NAME      VARCHAR(32) NOT NULL
  COMMENT '机构名称',
  CONTACT   VARCHAR(32) NOT NULL
  COMMENT '联系人',
  PHONE     VARCHAR(32) NOT NULL
  COMMENT '电话',
  EMAIL     VARCHAR(32) NOT NULL
  COMMENT '邮箱',
  AREA_CODE CHAR(6)     NOT NULL
  COMMENT '地区编码, 关联API_CN_AREAS'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '机构';

CREATE TABLE API_EQUIPMENTS (
  IMEI           VARCHAR(32) PRIMARY KEY
  COMMENT 'IMEI号',
  OGANIZATION    BIGINT      NOT NULL
  COMMENT '所属机构, 关联API_ORGANIZATIONS',
  SIM            VARCHAR(32) NOT NULL
  COMMENT 'SIM卡号',
  TERMINAL_MODEL VARCHAR(8)  NOT NULL
  COMMENT '终端型号, 比如: W01, Y02',
  TERMINAL_TYPE  VARCHAR(8)  NOT NULL
  COMMENT '终端类型, 比如: 手表',
  STATUS         INT         NOT NULL DEFAULT 1
  COMMENT '状态: 0: 关闭; 1: 开启'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '设备';

CREATE TABLE API_USERS_EQUIPMENTS_MAPPING (
  USER      BIGINT NOT NULL
  COMMENT '用户, 关联API_USERS',
  EQUIPMENT BIGINT NOT NULL
  COMMENT '设备, 关联API_EQUIPMENTS'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '用户和设备关联表';

CREATE UNIQUE INDEX UQ_API_USERS_EQUIPMENTS_MAPPING_U_E ON API_USERS_EQUIPMENTS_MAPPING (USER, EQUIPMENT);

CREATE TABLE API_INSTRUCTIONS (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(32)  NOT NULL
  COMMENT '名称',
  CONTENT     VARCHAR(128) NOT NULL
  COMMENT '内容, JSON格式, 比如: {"dhrupperlimit": 10, "dhrlowerlimit": 5}',
  DESCRIPTION VARCHAR(128) NOT NULL
  COMMENT '描述'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '指令集';

CREATE UNIQUE INDEX UQ_API_INSTRUCTIONS_NAME ON API_INSTRUCTIONS (NAME);

CREATE TABLE API_EQUIPMENTS_INSTRUCTIONS_MAPPING (
  EQUIPMENT   VARCHAR(32) NOT NULL
  COMMENT '设备, 关联API_EQUIPMENTS',
  INSTRUCTION BIGINT      NOT NULL
  COMMENT '指令, 关联API_INSTRUCTIONS'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '设备和指令集关联表';

CREATE INDEX IX_API_EQUIPMENTS_INSTRUCTIONS_MAPPING_E_I ON API_EQUIPMENTS_INSTRUCTIONS_MAPPING (EQUIPMENT, INSTRUCTION);

CREATE TABLE API_IMAGES (
  ID          BIGINT PRIMARY KEY,
  LARGE_URL   VARCHAR(256) NOT NULL
  COMMENT '大图片链接地址',
  MIDDLE_URL  VARCHAR(256) NOT NULL
  COMMENT '中图片链接地址',
  SMALL_URL   VARCHAR(256) NOT NULL
  COMMENT '小图片链接地址',
  CREATE_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '图片路径存储';

CREATE TABLE API_IMAGE_MAPPING (
  IMAGE      BIGINT NOT NULL
  COMMENT '图片存储',
  TYPE       INT COMMENT '类型: 0: 用户头像; 1: 其他',
  RELATED_ID BIGINT NOT NULL
  COMMENT '关联主体ID,比如TYPE为0,则关联API_USERS'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '图片关联';

CREATE INDEX IX_API_IMAGE_MAPPING_RELATED_ID_TYPE ON API_IMAGE_MAPPING (RELATED_ID, TYPE);

